### ISSUE TITLE
historical data for counterfactuals

### ISSUE THREAD

**Issue by mariacastillo21** [rmi-electricity/gencost#39]
get generator level data from 860, 923, and CAMD.

_What subset of generators?_
Intersection of 860 and CAMD

_Sources_
1) Use PUDL's 923 that already has allocations

_What do we do with CAMD?_
1) Allocate gross gen the same way net gen is calculated, but there are negative net generation values
2) Analogous process to boiler fuel allocation (line 1379)

- [x] set up structure (get exa by generator?)- columns we're gonna get, pf subplant id - generator id, not do aggregations
- [x] get 860
- [x] get PUDL's allocated generators
- [x] CAMD allocation process - allocate gross gen based on 923 fuel columns, using the BF schema 
- [x] construct get_exa_by_generator() 
- [x] integrate add_ba_code() to get_860_by_x()

PR tasks

- [x] get cems by generator - questions on scope (how do we allocate this information to the generator level without GF?)
- [x] cems by generator - do we need capacity merge? q: can we just merge on xwalk with plant / unit epa id
- [x] get 860 by x - combine age columns, tbd
- [x] move fuel allocation step to get exa by generator, remaining q

**Comment by mariacastillo21** [comment]
**adding entity ids**

@arengel, I'm having issues with integrating the add ba code function from the entity id script. I was thinking of adding this function to get_860_by_x(), but the columns needed to run add_ba_code() are utility_id_eia and balancing authority code eia, but gens_860 from pudl table only has the utility id eia column.

In the waterfall tests script, I see that you ran add_ba_code() onto gens_860m from pudl table, but that table isn't an option from me. 

How were you thinking of integrating what's needed to run add_ba_code to the waterfall process?

<img width="590" alt="Screenshot 2023-05-16 at 2 46 00 PM" src="https://github.com/rmi-electricity/gencost/assets/85949548/4b8878f1-c3da-4759-8e19-af7ee36a5e60">

**Comment by arengel** [comment]
Just checking in on this, let me know if there is an issue here remaining or if you are all set.
